# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, restart the server process.

# Site settings
# If you look in the HTML files, you will see them accessed via
# {{ site.title }}, {{ site.email }}, and so on.
title: Anna Filou | Web Designer, Illustrator
description: >- # this means to ignore newlines until "baseurl:"


# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed

permalink: pretty

# Website Section Text in all langs
web-heading-en: I'm a fan of lightweight websites that don't make use of heavy databases. # {{ site.web-heading-en }}
web-heading-de: Ich stehe auf kompakte Websites, die keine groÃŸen Datenbanken verwenden. # {{ site.web-heading-de }}
web-heading-gr: Îœ' Î±ÏÎ­ÏƒÎ¿Ï…Î½ ÎµÎ»Î±Ï†ÏÎ¹Î¬ site Ï€Î¿Ï… Î´Îµ Ï‡ÏÎµÎ¹Î¬Î¶Î¿Î½Ï„Î±Î¹ Ï€Î¿Î»ÏÏ€Î»Î¿ÎºÎµÏ‚ Î²Î¬ÏƒÎµÎ¹Ï‚ Î´ÎµÎ´Î¿Î¼Î­Î½Ï‰Î½ Î³Î¹Î± Î½Î± Î´Î¿Ï…Î»Î­ÏˆÎ¿Ï…Î½. # {{ site.web-heading-gr }}

web-subtitle-en: Instead, I build static sites that are much faster and more flexible, then make them work with a static CMS for content creation and on-the-go editing.
web-subtitle-de: Stattdessen erstelle ich statische Websites, die viel schneller und flexibler sind, und mache sie dann mit einem statischen CMS fÃ¼r die Inhaltserstellung und die Bearbeitung unterwegs nutzbar.
web-subtitle-gr: Î¦Ï„Î¹Î¬Ï‡Î½Ï‰ "ÏƒÏ„Î±Ï„Î¹ÎºÎ­Ï‚ Î¹ÏƒÏ„Î¿ÏƒÎµÎ»Î¯Î´ÎµÏ‚ Ï€Î¿Î»Ï Ï€Î¹Î¿ Î³ÏÎ®Î³Î¿ÏÎµÏ‚ ÎºÎ±Î¹ ÎµÏ…Î­Î»Î¹ÎºÏ„ÎµÏ‚. ÎœÎµÏ„Î¬ Ï„Î¹Ï‚ ÏƒÏ…Î½Î´Î­Ï‰ Î¼Îµ Î­Î½Î± ÏƒÏ„Î±Ï„Î¹ÎºÏŒ CMS Î³Î¹Î± Î½Î± ÎµÎ¯Î½Î±Î¹ ÎµÏÎºÎ¿Î»Î± ÎµÏ€ÎµÎ¾ÎµÏÎ³Î¬ÏƒÎ¹Î¼ÎµÏ‚ Î¼Î­ÏƒÏ‰ Î±Ï€Î»ÏÎ½ Î±ÏÏ‡ÎµÎ¯Ï‰Î½ ÎºÎµÎ¹Î¼Î­Î½Î¿Ï….

jam-en: Read more about the JAMstack
jam-de: Lesen Sie mehr Ã¼ber den JAMstack
jam-gr: Î”Î¹Î±Î²Î¬ÏƒÏ„Îµ ÏƒÏ‡ÎµÏ„Î¹ÎºÎ¬ Î¼Îµ Ï„Î¿ JAMstack

# About
# Skills
skills:
  - ğŸ’» Webflow
  - ğŸ”· Netlify CMS
  - ğŸ“Š Airtable Databases
  - ğŸ”¬ Jekyll & Liquid
  - ğŸ¨ Watercolor Illustration
  - ğŸ–‹ï¸ Digital Illustration
  - â­ Logo Design

# Languages ğŸ‘„
# colors: dark blue (default, don't write, blue, green)
languages:
  - name: ğŸ‡ºğŸ‡¸ English
    level: Fluent
    color: 
  - name: ğŸ‡©ğŸ‡ª German
    level: Proficient
    color: light-blue
  - name: ğŸ‡¬ğŸ‡· Greek
    level: Native
    color: green

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
